apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-message
    receivers:
      - uid: slack-alerts
        type: slack
        settings:
          recipient: {{ env }}-app-alerts
          username: loki-logging-alert
          icon_emoji: heart
          mentionUsers:
          mentionChannel: here
          url: {{ slack_webhook_urls[env] }}
          title: |
            {% raw %}{{ template "slackMessageTitle" . }}{% endraw +%}
          text: |
            {% raw %}{{ template "slackMessageBody" . }}{% endraw +%}
  - orgId: 1
    name: email
    receivers:
      - uid: email
        type: email
        settings:
          addresses: x@frever.com
          singleEmail: false
          message: Error message in Loki log
          subject: |
            {% raw %}{{ template "default.title" . }}{% endraw +%}

