apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-message
    group_by: ['grafana_folder', 'alertname']
    matchers:
      - severity =~ "warning|error|severe|critical"
    group_wait: 30s
    group_internval: 5m
    repeat_interval: 3h

