apiVersion: 1

templates:
  - orgID: 1
    name: slackMessageTitle
    template: |
      {{ define "slackMessageTitle" }}
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ if gt (.Alerts.Resolved | len) 0 }}, RESOLVED:{{ .Alerts.Resolved | len }}{{ end }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}
      {{ end }}
  - orgID: 1
    name: slackAlertMessage
    template: |
      {{ define "slackAlertMessage" }}
      {{ range . }}
      {{ range .Annotations.SortedPairs }}
      - {{ .Name }} = {{ .Value }}
      {{ end }}
      {{ if gt (len .GeneratorURL) 0 }}Source: {{ .GeneratorURL }}{{ end }}
      {{ if gt (len .SilenceURL) 0 }}Silence: {{ .SilenceURL }}{{ end }}
      {{ if gt (len .DashboardURL) 0 }}Dashboard: {{ .DashboardURL }}{{ end }}
      {{ if gt (len .PanelURL) 0 }}Panel: {{ .PanelURL }}{{ end }}
      %SEARCH_LINK%
      You might need to tweak the time range for the above link.
      {{ end }}
      {{ end }}
  - orgID: 1
    name: slackMessageBody
    template: |
      {{ define "slackMessageBody" }}

      {{ if gt (len .Alerts.Firing) 0 }}**Firing**
      {{ template "slackAlertMessage" .Alerts.Firing }}
      {{ end }}

      {{ if gt (len .Alerts.Resolved) 0 }}**Resolved**
      {{ template "slackAlertMessage" .Alerts.Resolved }}
      {{ end }}

      {{ end }}
