{
 "title": "Frever Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_duration_ms_bucket, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_server_duration_ms_bucket, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Server Response Time 99-Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Http Server Response Time 95-Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Http Server Response Time Average (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_server_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Client Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Http Client Response Time 99-Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_client_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Http Client Response Time 95-Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Http Client Response Time Average (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_client_duration_ms_bucket{namespace=\"$namespace\", service=\"$service\"}[$__rate_interval])))"
    }
   ]
  }
 ]
}