---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: {{ .Values.app.gitCommit }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: frever-{{ .Release.Name }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Release.Name }}
    alb.ingress.kubernetes.io/healthcheck-path: "/api"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.sslCertificateArn | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/name: cms-authorization
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cms-authorization
spec:
  rules:
    - host: "cms-authorization.frever-api.com"
      http:
        paths:
          - backend:
              service:
                name: cms-authorization
                port:
                  name: http
            path: /
            pathType: Prefix
