---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: {{ .Values.app.gitCommit }}
  labels:
    app.kubernetes.io/name: cms-authorization
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cms-authorization
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cms-authorization
  type: {{ .Values.app.serviceType }}
